import = ["~/.config/alacritty/cyberdream.toml"]

[env]
TERM = "xterm-256color"


[window]
padding.x = 2
padding.y = 2
dimensions = { columns = 340, lines = 100 }

decorations = "buttonless"

opacity = 0.7
blur = true


# option_as_alt = "Both"

[font]
normal.family = "DroidSansMono Nerd Font"

size = 15
